name: Deploy to EC2

on:
  push:
    branches: [testing]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4  # or your version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build standalone
        run: |
          pnpm run prisma-generate
          pnpm build

      - name: Archive standalone output
        run: |
          tar -czf next.tar.gz .next

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_SSH_HOST }}
          username: ${{ secrets.AWS_EC2_SSH_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          source: "next.tar.gz"
          target: "~/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_SSH_HOST }}
          username: ${{ secrets.AWS_EC2_SSH_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/app

            rm -rf server
            mkdir -p server
            tar -xzf next.tar.gz -C server

            pm2 delete website || true
            pm2 start ecosystem.config.js
